### ISSUE TITLE
footer样式显示异常

### ISSUE THREAD

**Issue by Akimio521** [wleelw/Hexo-theme-solitude#104]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![image](https://github.com/wleelw/Hexo-theme-solitude/assets/77880495/a8512642-f075-4642-862b-85ad89127040)

### 终端日志 📒

<此处粘贴终端日志>
ERROR TypeError: D:\Blog\themes\solitude\layout\includes\widgets\page\about\authorinfo.pug:5
    3| .author-info
    4|     .author-tag-left
  > 5|         each tag in authorinfo.leftTags
    6|             span.author-tag= tag
    7|     .author-img
    8|         img(src=authorinfo.image)

Cannot read properties of undefined (reading 'leftTags')
    at eval (eval at wrap (D:\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:3292:26)
    at eval (eval at wrap (D:\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:3312:4)
    at template (eval at wrap (D:\Blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:14952:7)
    at _View._compiled (D:\Blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\Blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\Blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:737:12)
    at resume_ (node:internal/streams/readable:1255:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  path: 'D:\\Blog\\themes\\solitude\\layout\\includes\\widgets\\page\\about\\authorinfo.pug'
}

**Comment by wleelw** [comment]
解决了吗

**Comment by Akimio521** [comment]
> 解决了吗

解决了，配置文件被我改错了，重新cp一份重写就好了
