### ISSUE TITLE
开发版每次启动报错

### ISSUE THREAD

**Issue by RicharPao** [wleelw/hexo-theme-solitude#113]
### 前置确认

- [x] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

开发板 (dev)

### 问题描述 😯

截止到 2024年1月24日 ，使用开发版时每次 `hexo g` `hexo s` 等命令都有下面的报错
![image](https://github.com/wleelw/hexo-theme-solitude/assets/99643174/2c640ed5-3ab9-4fbe-9658-f5b390f05053)

### 终端日志 📒

PS E:\Blog\VacuoleBlog> hexo --version
INFO  Validating config
ERROR Script load failed: themes\solitude\scripts\helper\getArchiveLength.js
Error: Cannot find module 'moment'
Require stack:
- E:\Blog\VacuoleBlog\themes\solitude\scripts\helper\getArchiveLength.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at req (E:\Blog\VacuoleBlog\node_modules\.pnpm\hexo@7.1.1\node_modules\hexo\dist\hexo\index.js:241:31)       
    at E:\Blog\VacuoleBlog\themes\solitude\scripts\helper\getArchiveLength.js:1:87
    at E:\Blog\VacuoleBlog\node_modules\.pnpm\hexo@7.1.1\node_modules\hexo\dist\hexo\index.js:249:20
    at tryCatcher (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (E:\Blog\VacuoleBlog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
INFO
  ===================================================================
       #####  ####  #     #####  ###### #     # ######   ######
      #      #    # #       #      #    #     # #      # #
       ##### #    # #       #      #    #     # #      # ######
           # #    # #       #      #    #     # #      # #
      ######  ####  ##### #####    #      ###   ######   ######
                            1.3.1
  ===================================================================
  主题链接：https://github.com/wleelw/Hexo-theme-solitude

hexo: 7.1.1
hexo-cli: 4.3.1
os: win32 10.0.22621
node: 18.17.1
acorn: 8.8.2
ada: 2.5.0
ares: 1.19.1
brotli: 1.0.9
cldr: 43.0
icu: 73.1
llhttp: 6.0.11
modules: 108
napi: 9
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.10+quic
simdutf: 3.2.12
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.18
v8: 10.2.154.26-node.26
zlib: 1.2.13.1-motley
PS E:\Blog\VacuoleBlog>

**Comment by RicharPao** [comment]
呃，可能控制台输出的字符包含一些md的格式，有点奇怪

**Comment by RicharPao** [comment]
没用过稳定版，两次使用开发版都有报错，如果是正常现象或者已经在修复了请直接close

**Comment by wleelw** [comment]
在群里吗，方便给我d个消息，我给你远程看下是哪里的问题

**Comment by wleelw** [comment]
开发版在不断变动，有时候改了东西不会第一时间更新文档

**Comment by RicharPao** [comment]
😅电脑配置太低了，远程卡的不行
你可以开一个文件夹试一下，就是dev分支，没有进行任何改动，只是把站点配置文件里的主题改成了solitude
启动报错，这个moment...看着像
![image](https://github.com/wleelw/hexo-theme-solitude/assets/99643174/6c8e4ce7-f2f5-4abd-8e5c-35f188e5f52b)

**Comment by wleelw** [comment]
moment 是一个时间格式转换，你看看是不是 即刻短文，或者哪里使用了时间格式，写错了

**Comment by RicharPao** [comment]
还有个问题就是，主题所使用的图标库class在哪能看。
对了，图标是不是只引入了主题所需要的，remixicon中其他的没有吧？

**Comment by wleelw** [comment]
> 还有个问题就是，主题所使用的图标库class在哪能看。 对了，图标是不是只引入了主题所需要的，remixicon中其他的没有吧？

加群看

**Comment by wleelw** [comment]
> 绝对不可能，我看到这个报错之前执行的操作
> 
> 1. hexo init
> 2. 使用git安装dev分支的主题
> 3. 在_config.yml中修改theme: solitude
> 4. hexo g && hexo s
>    **没有对主题进行任何配置**

我没有报错你的信息

**Comment by RicharPao** [comment]
使用git安装主题之后在根目录运行 `npm i`来安装一遍依赖和包
