### ISSUE TITLE
启用solitude主题后，执行hexo g时会报错。是不是主题中的css语法和stylus插件有冲突。

### ISSUE THREAD

**Issue by zeallean** [wleelw/hexo-theme-solitude#139]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://docs.wzsco.top/FAQ.html)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

MacOS

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

安装了最新版本的hexo，也安装了hexo-renderer-pug hexo-renderer-stylus 插件，默认主题执行没有任何问题，但是启用solitude主题后，执行hexo g时会报错。应该是主题中的语法和stylus插件有冲突。
版本信息：
hexo: 7.1.1
hexo-cli: 4.3.1
os: darwin 19.6.0 10.15.7

node: 21.6.2
acorn: 8.11.3
ada: 2.7.4
ares: 1.20.1
base64: 0.5.1
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 44.0
icu: 74.1
llhttp: 9.1.3
modules: 120
napi: 9
nghttp2: 1.58.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.13+quic
simdjson: 3.6.3
simdutf: 4.0.8
tz: 2023c
undici: 5.28.3
unicode: 15.1
uv: 1.48.0
uvwasi: 0.0.19
v8: 11.8.172.17-node.19
zlib: 1.3.0.1-motley-40e35a7

### 终端日志 📒

<此处粘贴终端日志>
ERROR Asset render failed: css/index.css
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Hexo.<anonymous> (/Users/my/blog/node_modules/hexo-theme-solitude/scripts/helper/stylus.js:25:24)
    at Filter.execSync (/Users/my/blog/node_modules/hexo/dist/extend/filter.js:72:36)
    at Hexo.execFilterSync (/Users/my/blog/node_modules/hexo/dist/hexo/index.js:397:35)
    at Renderer.<anonymous> (/Users/my/blog/node_modules/hexo-renderer-stylus/lib/renderer.js:57:24)
    at Renderer.use (/Users/my/blog/node_modules/stylus/lib/renderer.js:188:8)
    at Hexo.stylusFn (/Users/my/blog/node_modules/hexo-renderer-stylus/lib/renderer.js:57:6)
    at Hexo.promisified (/Users/my/blog/node_modules/bluebird/js/release/promisify.js:223:16)
    at /Users/my/blog/node_modules/hexo/dist/hexo/render.js:73:28
    at tryCatcher (/Users/my/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/my/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/my/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/my/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/my/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/my/blog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/my/blog/node_modules/bluebird/js/release/async.js:86:9)

**Comment by wleelw** [comment]
<img width="762" alt="image" src="https://github.com/wleelw/hexo-theme-solitude/assets/74389842/5d734c26-d682-4e3f-a6e6-ee215d193787">
这部分需要打开

**Comment by wleelw** [comment]
已在dev分支修改，具体以亦封合并后代码参考

**Comment by liguangni** [comment]
> 已在dev分支修改，具体以亦封合并后代码参考

现在的yaml文件注释部分缩进有点问题。原来的时候，解开注释就可以直接使用，新版本需要自己调整缩进。
希望一块修复一下
![搜狗截图20240229093605](https://github.com/wleelw/hexo-theme-solitude/assets/11803126/e1d2aa26-4b46-4296-9d36-6534057e236c)

**Comment by wleelw** [comment]
> > 已在dev分支修改，具体以亦封合并后代码参考
> 
> 现在的yaml文件注释部分缩进有点问题。原来的时候，解开注释就可以直接使用，新版本需要自己调整缩进。 希望一块修复一下 ![搜狗截图20240229093605](https://private-user-images.githubusercontent.com/11803126/308763628-e1d2aa26-4b46-4296-9d36-6534057e236c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjYyODAsIm5iZiI6MTcwOTI2NTk4MCwicGF0aCI6Ii8xMTgwMzEyNi8zMDg3NjM2MjgtZTFkMmFhMjYtNGI0Ni00Mjk2LTlkMzYtNjUzNDA1N2UyMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA0MDYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZGY5NWU3ZDczNGIxNDE5YzMyOWU2NWM2NWU4OTU5YWEyY2IxY2JkMTcwMDNkODEzZDc3ZTljOGVhNWQ0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j7HDpbwrq5OEys9V3w73avOK9HBjNi5cifzDdiFF41k)

具体根据更新后的文档格式为据，配置文件中注释仅为演示
